# Generated by Django 4.2.18 on 2025-02-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0002_children_updated_at_alter_children_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "pharmacy_name",
                    models.CharField(max_length=100, verbose_name="약국명"),
                ),
                (
                    "prescription_number",
                    models.CharField(max_length=100, verbose_name="처방전 번호"),
                ),
                ("prescription_date", models.DateField(verbose_name="처방일자")),
                (
                    "pharmacy_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="약국주소"
                    ),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=50, verbose_name="총액"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="투약일수"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="children.children",
                        verbose_name="아동",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방전",
                "verbose_name_plural": "처방전 목록",
                "db_table": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_column="medicine_name", max_length=100, verbose_name="약품명"
                    ),
                ),
                ("dosage", models.IntegerField(verbose_name="복용량")),
                (
                    "frequency",
                    models.IntegerField(default=0, null=True, verbose_name="투약횟수"),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, null=True, verbose_name="투약일수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        db_column="prescription_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="registerPrescription.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방약",
                "verbose_name_plural": "처방약 목록",
                "db_table": "medicines",
                "ordering": ["created_at"],
            },
        ),
    ]
