# Generated by Django 4.2.18 on 2025-02-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registerPrescription", "0004_alter_prescription_prescription_number"),
    ]

    operations = [
        migrations.RunSQL(
            # 아무 작업도 하지 않음 (이미 prescription_id가 올바르게 설정되어 있으므로)
            sql='SELECT 1;',  # 더미 쿼리
            reverse_sql='SELECT 1;'
        ),
    ]
